language: go

# S: Build Lifecycle
install:
  - go get github.com/InkProject/ink
  # - ink build $GOPATH/src/github.com/InkProject/ink/template
  - ink build
# before_script

script:
  - cd ./public
  - git init
  - git config user.name "boyzhaotian"
  - git config user.email "13426031783@139.com"
  - git add .
  - git commit -m "update public"
  - git push --force --quiet "https://${Github_Token}@${GH_REF}" master:master

# after-script:
# E: Build Lifecycle

branches:
  only:
    - blog-source
env:
  global:
    - GH_REF: github.com/boyzhaotian/blog